version: '3.1'

networks:
  front-tier:
  back-tier:
  external:

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/persistence:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager
      - transmission-exporter 
    networks:
      - back-tier
      - external
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/persistence:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

  transmission-exporter:
    image: metalmatze/transmission-exporter
    ports:
      - 19091:19091
    env_file: ./transmission-exporter/.env
    networks:
      - back-tier
      - external

  speedport-exporter:
    build: ./speedport-exporter
    image: speedport-exporter:latest
    depends_on:
      - prometheus
    ports:
      - 8000:8000
    env_file:
      - ./speedport-exporter/.env
    networks:
      - back-tier
      - external
