{
 "title": "Speedport Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Upstream Rate (Mbps)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upstream_current_rate / 1024" }
   ]
  },
  {
   "title": "Downstream Rate (Mbps)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "downstream_current_rate / 1024" }
   ]
  },
  {
   "title": "Upstream SNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upstream_snr" }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "downstream_snr" }
   ]
  },
  {
   "title": "Upstream Attenuation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upstream_attenuation / 10" }
   ]
  },
  {
   "title": "Downstream Attenuation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "downstream_attenuation / 10" }
   ]
  },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "status" }
   ]
  },
  {
   "title": "Current Connection Type",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "connection_type" }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "status" }
   ]
  },
  {
   "title": "Connection Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "connection_type" }
   ]
  },
  {
   "title": "Upstream CRC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upstream_fec_errors" }
   ]
  },
  {
   "title": "Downstream CRC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "downstream_crc_errors" }
   ]
  },
  {
   "title": "Upstream FEC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upstream_fec_errors" }
   ]
  },
  {
   "title": "Downstream FEC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "downstream_fec_errors" }
   ]
  }
 ]
}